### PR TITLE
Move to using Echo for Logging

### PR DESCRIPTION
**Pull request by EnochMiningCorporation**
Update 1.082 has introduced a new method for IMyProgrammableBlock:

Action<string> Echo;

Which will write the string to the Control Panel DetailedInfo area (i.e. where exceptions currently display text), but without throwing an exception and blocking the rest of and any further runs of the script (currently requires recompile to run again).

I'd say it's still warranted to provide an exception throwing mechanism, for times when it is desirable to halt ongoing runs of the script. So need to think of the best places to use Echo in this set:

DebugDump/DebugDumpProperties/DebugDumpActions
EasyUtils.Log

I think using Echo for Log is a no brainer. For DebugDump~, well, it could get messy to use Echo for that. What do you think?

### CODE REVIEW

**Comment by rockyjvec** [comment]
I added the Echo function to the EasyAPI class so it can be called anywhere inside an EasyAPI class.  All of those DebugDump functions can return a string if you pass in false to them.  So you could echo the actions like:
Echo(Blocks.DebugDumpActions(false));

The difficulty trying to use it in the Log() function will be that you can't access non-static methods from inside that class.  So you would have to somehow initialize the EasyUtils class with the Echo function like I had to do with EasyAPI.  Unless you know of a better way.  I hate to have to pass everything into the constructor like that.

**Comment by EnochMiningCorporation** [comment]
ah good point, I was coding this up last night but got distracted by game play haha. Something to consider is that if you add any chars that are over the 80000 count via Echo, it will clear previous string and only display the new string. So I was setting up a sort of ring buffer that would always keep the string passed to Echo under 80001 chars (removing as many lines from start as needed to allow room for the new line at end).

**Comment by EnochMiningCorporation** [comment]
Odd thing I've found is that although Echo writes to DetailedInfo, the echoed string cannot be read back via DetailedInfo.

**Comment by rockyjvec** [comment]
Strange.  That's a good idea to set up a ring buffer.  I wish all the Program class properties were public, like Me, Echo, etc.   Then I could just pass "this" into the easyapi constructor instead of having to pass them in individually.

**Comment by EnochMiningCorporation** [comment]
cool, assigning a pull-request to this issue worked! FYI to do that trick, checkout these resources:

http://stackoverflow.com/a/7841960/1085264
https://github.com/github/hub

I downloaded hub (for windows), added to PATH in System Variables, and this in command line:

```
hub pull-request -i 6 -b rockyjvec:master -h EnochminingCorporation:master https://github.com/rockyjvec/EasyAPI/pull/6
```

...though it might be as simple as:

```
hub pull-request https://github.com/rockyjvec/EasyAPI/pull/6
```

**Comment by EnochMiningCorporation** [comment]
oh and here's a snippet to show usage of the new Log feature:

```
public class Example : EasyAPI  
{  
    public Example(IMyGridTerminalSystem grid, IMyProgrammableBlock me, Action<string> echo, TimeSpan elapsedTime) : base(grid, me, echo, elapsedTime)  
    {  
        Every(1 * EasyAPI.Seconds, logTime); 
    }  

    public void logTime() { 
        EasyUtils.Log("time", this.Echo, (IMyProgrammableBlock)Self.Block, DateTime.Now.ToString("yy/MM/dd HH:mm:ss")); 
        //EasyUtils.Log("time"); 
    } 
}  
```

It's a bit raw, but we could easily provide a simpler API that hides the rawness. Hoping to get your eyes on it first.

**Comment by rockyjvec** [comment]
Nice! I just merged it.  I'll update the workshop script now.  Yeah, I haven't found a good way to access the Echo function without passing it in somehow.  That works as good as anything I've found so far.

**Comment by rockyjvec** [comment]
Okay, I updated the workshop script, and updated all my documentation as best as I could to reference the new constructor with ElapsedTime.  Hopefully we won't need to change that many more times, lol.

**Pull request merged**
